dataset:
  name: ODE_Lorenz
  pair_id: [1]
model:
  name: SINDy
  POD_modes: 3
  differentiation_method: 'finite_difference'
  differentiation_method_order: 2
  feature_library: 'polynomial'
  feature_library_order: 4
  optimizer: 'STLSQ'
  threshold: 1.0
  alpha: 0.05