dataset:
  name: ODE_Lorenz
  pair_id: [1]
model:
  name: SINDy
  POD_modes: 3
  differentiation_method: 'finite_difference'
  differentiation_method_order: 5
  feature_library: 'polynomial'
  feature_library_order: 2
  optimizer: 'FROLS'
  threshold: 0.1
  alpha: 0.05