dataset:
  name: ODE_Lorenz
  pair_id: "all"
model:
  name: SINDy
  POD_modes: 3
  differentiation_method: 'kalman'
  differentiation_method_order: 2
  feature_library: 'polynomial'
  feature_library_order: 3
  optimizer: 'FROLS'
  threshold: 1.0
  alpha: 0.05