dataset:
  name: ODE_Lorenz
  pair_id: 'all'
model:
  name: SINDy
  POD_modes: 3
  differentiation_method: 'finite_difference'
  differentiation_method_order: 2
  feature_library: 'polynomial'
  feature_library_order: 4
  threshold: 0.5
  optimizer: 'STLSQ'