dataset:
  name: ODE_Lorenz
  pair_id: [4]
model:
  POD_modes: 3
  alpha: 0.1
  differentiation_method: spectral
  differentiation_method_order: 2
  feature_library: polynomial
  feature_library_order: 2
  name: SINDy
  optimizer: FROLS
  threshold: 1.0