dataset:
  name: ODE_Lorenz
  pair_id: [6]
model:
  POD_modes: 3
  alpha: 0.05
  differentiation_method: finite_difference
  differentiation_method_order: 4
  feature_library: polynomial
  feature_library_order: 2
  name: SINDy
  optimizer: STLSQ
  threshold: 0.1
