dataset:
  name: ODE_Lorenz
  pair_id: [1,2,3,4,5,6,7,8,9]
model:
  name: SINDy
  train_split: 0.8
  seed: 0
  n_trials: 3
  method: 'constant'
hyperparameters: # Specify hyperparameters and ranges
  POD_modes:
    type: randint
    lower_bound: 3
    upper_bound: 3
  differentiation_method:
    type: choice
    values: ["finite_difference", "savitzky_golay", "spline", "trend_filtered", "spectral", "kalman"]
  differentiation_method_order:
    type: randint
    lower_bound: 1
    upper_bound: 2
  feature_library:
    type: choice
    values: ["polynomial", "Fourier", "mixed"]
  feature_library_order:
    type: randint
    lower_bound: 1
    upper_bound: 10
  optimizer:
    type: choice
    values: ["STLSQ", "SR3", "SSR", "FROLS"]
  threshold:
    type: loguniform
    lower_bound: 1e-4
    upper_bound: 1e-0
  alpha:
    type: loguniform
    lower_bound: 1e-4
    upper_bound: 1e-0